#!/system/bin/sh
find /storage/emulated/0 -type d -exec chown media_rw:media_rw '{}' \;  -exec chmod 0775 '{}' \; 
find /storage/emulated/0 -type f -exec chown media_rw:media_rw '{}' \;  -exec chmod 0664 '{}' \;
