#!/system/bin/sh

cd /sdcard/
#-----------------Limpieza------------------
#Borrar Archivos Viejos
find /sdcard/Pictures/Screenshots -mtime +30 -type f | xargs -0 rm -f
find /sdcard/WhatsApp/Media -mtime +60 -type f | xargs -0 rm -f
rm -f /sdcard/WhatsApp/Profile\ Pictures/*.jpg
rm -fr UnityAdsVideoCache
find /sdcard/Download/Apps/ -type f -iname google | xargs -0 rm -f
find /sdcard/Download/Apps/ -type f -iname whatsapp | xargs -0 rm -f

TWEAKS="/sdcard/Download/Zips/My-Tweaks*"
GAPPS="/sdcard/Download/Zips/BaNkS-Dynamic-*"
ROM="/sdcard/Download/Zips/chroma_mako-*"
KERNEL="/sdcard/Download/Zips/hC-*"
if [ "`echo $TWEAKS`" != "$TWEAKS" ]; then
	ls $TWEAKS | sort -r | sed -n '1!p' | xargs rm -f
fi
if [ "`echo $GAPPS`" != "$GAPPS" ]; then
	ls $GAPPS | sort -r | sed -n '1!p' | xargs rm -f
fi
if [ "`echo $ROM`" != "$ROM" ]; then
	ls $ROM | sort -r | sed -n '1!p' | xargs rm -f
fi
if [ "`echo $KERNEL`" != "$KERNEL" ]; then
	ls $KERNEL | sort -r | sed -n '1!p' | xargs rm -f
fi

# Limpiar Downloads
NFILES=$(find /sdcard/Download/ -maxdepth 1 -type f | wc -l)
if [ $NFILES != "0" ]; then

	mkdir -p /sdcard/Download/Zips
	if [ "`echo /sdcard/Download/*.zip`" != "/sdcard/Download/*.zip" ]; then
		mv /sdcard/Download/*.zip /sdcard/Download/Zips/
	fi
	
	mkdir -p /sdcard/Download/Apps
	if [ "`echo /sdcard/Download/*.apk`" != "/sdcard/Download/*.apk" ]; then
		mv /sdcard/Download/*.apk /sdcard/Download/Apps/
	fi
	
	mkdir -p /sdcard/Documents/
	if [ "`echo /sdcard/Download/*.doc /sdcard/Download/*.docx`" != "/sdcard/Download/*.doc /sdcard/Download/*.docx" ]; then
		mv /sdcard/Download/*.doc* /sdcard/Documents/
	fi
	if [ "`echo /sdcard/Download/*.xls /sdcard/Download/*.xlsx`" != "/sdcard/Download/*.xls /sdcard/Download/*.xlsx" ]; then
		mv /sdcard/Download/*.xls* /sdcard/Documents/
	fi
	if [ "`echo /sdcard/Download/*.ppt /sdcard/Download/*.pptx`" != "/sdcard/Download/*.ppt /sdcard/Download/*.pptx" ]; then
		mv /sdcard/Download/*.ppt* /sdcard/Documents/
	fi
	if [ "`echo /sdcard/Download/*.pdf`" != "/sdcard/Download/*.pdf" ]; then
		mv /sdcard/Download/*.pdf /sdcard/Documents/
	fi
	
	mkdir -p /sdcard/Pictures/Downloaded\ Pictures
	if [ "`echo /sdcard/Download/*.jpg`" != "/sdcard/Download/*.jpg" ]; then
		mv /sdcard/Download/*.jpg /sdcard/Pictures/Downloaded\ Pictures
	fi
	if [ "`echo /sdcard/Download/*.png`" != "/sdcard/Download/*.png" ]; then
		mv /sdcard/Download/*.png /sdcard/Pictures/Downloaded\ Pictures
	fi
	if [ "`echo /sdcard/Download/*.gif`" != "/sdcard/Download/*.gif" ]; then
		mv /sdcard/Download/*.gif /sdcard/Pictures/Downloaded\ Pictures
	fi
fi
