#!/system/bin/sh

cd /storage/emulated/0
#-----------------Limpieza------------------
#Borrar Archivos Viejos
find ./Pictures/Screenshots -mtime +30 -type f | xargs rm -f
find ./WhatsApp/Media -mtime +60 -type f | xargs rm -f
rm -f ./WhatsApp/Profile\ Pictures/*.jpg
rm -fr UnityAdsVideoCache
find ./Download/Apps/ -type f -iname *google* | xargs rm -f
find ./Download/Apps/ -type f -iname *whatsapp* | xargs rm -f

MAKOTOOLS="./Download/Zips/Mako-Tools*"
GAPPS="./Download/Zips/BaNkS-Dynamic-*"
ROM="./Download/Zips/chroma_mako-*"
KERNEL="./Download/Zips/hC-*"
if [ "`echo $MAKOTOOLS`" != "$MAKOTOOLS" ]; then
	ls $MAKOTOOLS | sort -r | sed -n '1!p' | xargs rm -f
fi
if [ "`echo $GAPPS`" != "$GAPPS" ]; then
	ls $GAPPS | sort -r | sed -n '1!p' | xargs rm -f
fi
if [ "`echo $ROM`" != "$ROM" ]; then
	ls $ROM | sort -r | sed -n '1!p' | xargs rm -f
fi
if [ "`echo $KERNEL`" != "$KERNEL" ]; then
	ls $KERNEL | sort -r | sed -n '1!p' | xargs rm -f
fi

# Limpiar Downloads
NFILES=$(find ./Download/ -maxdepth 1 -type f | wc -l)
if [ $NFILES != "0" ]; then

	mkdir -p ./Download/Zips
	if [ "`echo ./Download/*.zip`" != "./Download/*.zip" ]; then
		mv ./Download/*.zip ./Download/Zips/
	fi
	
	mkdir -p ./Download/Apps
	if [ "`echo ./Download/*.apk`" != "./Download/*.apk" ]; then
		mv ./Download/*.apk ./Download/Apps/
	fi
	
	mkdir -p ./Documents/
	if [ "`echo ./Download/*.doc ./Download/*.docx`" != "./Download/*.doc ./Download/*.docx" ]; then
		mv ./Download/*.doc* ./Documents/
	fi
	if [ "`echo ./Download/*.xls ./Download/*.xlsx`" != "./Download/*.xls ./Download/*.xlsx" ]; then
		mv ./Download/*.xls* ./Documents/
	fi
	if [ "`echo ./Download/*.ppt ./Download/*.pptx`" != "./Download/*.ppt ./Download/*.pptx" ]; then
		mv ./Download/*.ppt* ./Documents/
	fi
	if [ "`echo ./Download/*.pdf`" != "./Download/*.pdf" ]; then
		mv ./Download/*.pdf ./Documents/
	fi
	
	mkdir -p ./Pictures/Downloaded\ Pictures
	if [ "`echo ./Download/*.jpg`" != "./Download/*.jpg" ]; then
		mv ./Download/*.jpg ./Pictures/Downloaded\ Pictures
	fi
	if [ "`echo ./Download/*.png`" != "./Download/*.png" ]; then
		mv ./Download/*.png ./Pictures/Downloaded\ Pictures
	fi
	if [ "`echo ./Download/*.gif`" != "./Download/*.gif" ]; then
		mv ./Download/*.gif ./Pictures/Downloaded\ Pictures
	fi
fi
