#!/system/bin/sh

#Kill media server to save battery
#killall -9 android.process.media
#killall -9 mediaserver

#Cleaner script
rm -f /data/*.log
rm -f /data/*.txt
rm -f /data/log/*.log
rm -f /data/log/*.txt
rm -f /dev/log/*
rm -f /data/anr/*.*
rm -f /cache/*.apk
rm -f /cache/*.tmp
rm -f /cache/recovery/*
rm -f /data/local/*.apk
rm -f /data/local/*.log
rm -f /data/local/tmp/*.apk
rm -f /data/backup/pending/*.tmp
rm -f /data/system/usagestats/*.txt
rm -f /data/system/dropbox/*.txt
rm -f /data/tombstones/*.log
rm -f /data/tombstones/*.txt
rm -f /data/dalvik-cache/*.apk
rm -f /data/dalvik-cache/*.tmp
rm -rf /sdcard/LOST.DIR

# <<< Under Volt >>>
echo 94500 725000 > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo 189000 725000 > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo 243000 750000 > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo 384000 750000 > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo 432000 775000 > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo 486000 775000 > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo 540000 800000 > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo 594000 800000 > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo 648000 825000 > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo 702000 825000 > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo 756000 875000 > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo 810000 875000 > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo 864000 900000 > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo 918000 900000 > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo 972000 925000 > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo 1026000 925000 > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo 1080000 975000 > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo 1134000 975000 > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo 1188000 1000000 > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo 1242000 1000000 > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo 1296000 1025000 > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo 1350000 1025000 > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo 1404000 1037500 > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo 1458000 1037500 > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels
echo 1512000 1037500 > /sys/devices/system/cpu/cpufreq/vdd_table/vdd_levels

# CPU min
echo 94500 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
echo 94500 > /sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq
echo 94500 > /sys/devices/system/cpu/cpu2/cpufreq/scaling_min_freq
echo 94500 > /sys/devices/system/cpu/cpu3/cpufreq/scaling_min_freq

# <<< Governor >>>
echo 0 > /sys/devices/system/cpu/cpufreq/conservative/input_boost_freq
echo 0 > /sys/devices/system/cpu/cpufreq/conservative/input_boost_duration

# <<< Temperature throtle >>>
echo 50 > /sys/module/msm_thermal/parameters/temp_max

# <<< Vibrator Strength >>>
#echo 70 > /sys/class/timed_output/vibrator/amp

# <<< Disable wakelock >>>
echo 0 > /sys/module/wakeup/parameters/enable_msm_hsic_ws

# <<< DT2W >>>
echo 1 > /sys/devices/virtual/input/lge_touch/dt_wake_enabled
echo 1 > /sys/devices/virtual/input/lge_touch/dt_wake_pwr_disable
#echo 1 > /sys/devices/virtual/misc/touchwake/enabled
#echo 10000 > /sys/devices/virtual/misc/touchwake/delay
